/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mohammad_swingboost_NativeController */

#ifndef _Included_me_mohammad_swingboost_NativeController
#define _Included_me_mohammad_swingboost_NativeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    getHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_me_mohammad_swingboost_NativeController_getHandle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_initialize
  (JNIEnv *, jobject);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressValue
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressValue
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressStateNormal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressStateNormal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressStateError
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressStateError
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressStatePaused
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressStatePaused
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressStateNone
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressStateNone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_mohammad_swingboost_NativeController
 * Method:    setTaskbarProgressStateIndeterminate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_mohammad_swingboost_NativeController_setTaskbarProgressStateIndeterminate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
